### ISSUE TITLE
Logstash Crashing, v. 2.1.0, NoMethodError: undefined method `<=' for nil:NilClass

### ISSUE THREAD

**Issue by myunxi** [logstash-plugins/logstash-codec-multiline#35] opened 2016-05-13 07:00 UTC
NoMethodError: undefined method `<=' for nil:NilClass
  map_cleanup at /LAPPOMS/usr/ppap_oms/logstash/logstash-2.1.0/vendor/bundle/jruby/1.9/gems/logstash-codec-multiline-2.0.4/lib/logstash/codecs/identity_map_codec.rb:193
    delete_if at org/jruby/RubyHash.java:1642
  map_cleanup at /LAPPOMS/usr/ppap_oms/logstash/logstash-2.1.0/vendor/bundle/jruby/1.9/gems/logstash-codec-multiline-2.0.4/lib/logstash/codecs/identity_map_codec.rb:192
        start at /LAPPOMS/usr/ppap_oms/logstash/logstash-2.1.0/vendor/bundle/jruby/1.9/gems/logstash-codec-multiline-2.0.4/lib/logstash/codecs/identity_map_codec.rb:53
         loop at org/jruby/RubyKernel.java:1479
        start at /LAPPOMS/usr/ppap_oms/logstash/logstash-2.1.0/vendor/bundle/jruby/1.9/gems/logstash-codec-multiline-2.0.4/lib/logstash/codecs/identity_map_codec.rb:50

**Comment by myunxi** [comment] 2016-05-31 06:38
I use the cpulimit to limit the cpu usage,The cpulimit use SIGCONT and SIGSTOP to limit cpu.If I do not  use cpulimt,the problem never happened.

**Comment by guyboertje** [comment] 2017-06-01 14:40
Duplicate of #32

**Closed as completed by guyboertje** 2017-06-01 14:40 UTC
Labels: question, needs details
