### ISSUE TITLE
Configurable flush interval

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-codec-multiline#15] opened 2015-11-18 18:08 UTC
In https://github.com/logstash-plugins/logstash-codec-multiline/pull/13, we added the evict_timeout for flushing to flush the last data collected if there is no need new data appended to a file.  However, this is hardcoded to 1 hr right now.  We have requirements in the field for near real-time.  Can we expose this as a configuration (and maybe cap the minimum flush interval to something sensible)?

**Comment by guyboertje** [comment] 2015-11-19 07:29
Maybe a duplicate or related to #11.

This is kind of doable.

Please note the following:
- The Multiline codec when used in an input is incapable of flushing out-of-band events into the pipeline because of design problems with the pipeline <-> input interaction.
- Eviction stuff was added to the IdentityMapCodec object.
- The IdentityMapCodec is not a real codec, it does not subclass `LogStash::Codecs::Base` and therefore does not have config options. It was designed as a transparent wrapper to sit between an input and ANY codec where discreet 'streams' of data from an input needs separation.
- It exists in this repo as a convenience because multiline is the first and obvious codec that would benefit.  It will probably move.
- The eviction and flush was added because flush is part of the public API of a codec.
- The default settings were chosen after some debate and can be set programatically by the input code that chooses to use IdentityMapCodec to wrap its codec.

In order to do this we could use a config option from the input. This makes sense because A) of the point above and B) the input understands the context of the data being ingested better than the codec.

It is, of course, possible to use a config option from the codec but then it needs be one that exists in all codecs and therefore defined in `LogStash::Codecs::Base`. I did not do this because I wanted this initial release to be independent of a LS core version until we ironed out any problems.

@suyograo, @ph, @colinsurprenant - WDYT?

**Comment by ph** [comment] 2015-11-19 14:34
There is another problem related to the `flush`, the current implementation the identity map memorize the block on the first decode block and use the same one when the tick is called. 

This should work normally in the majority of the plugins but in the context of beats this could be problematic, since the queue can raise an exception and kill the eviction thread.

Maybe we should add a way to define a custom eviction method?

**Comment by ph** [comment] 2015-11-19 14:44
I am wondering maybe we can change how the eviction work, I see it as two problems.

A) **Multiline:** Should I flush the content of my buffer based on a max_ages?

B) **IdentityMap:** Should I remove unused codecs from my hash?

If we define the _unused codec_ concept from **B** by _if the codec doesn't have any buffered data_ we can say its not in use and we can free it. This make the codec responsible to flush itself on a periodic calls.

Also in this scenario we need to be able to define the call back that will receive the tick.

**Comment by guyboertje** [comment] 2015-11-19 14:56
@ph - re: pushing events to the queue raising exceptions, do you suspect this or is the raised exception by design?

Either way I need to protect my Cleaner thread.

**Comment by ph** [comment] 2015-11-19 15:03
@guyboertje its by design and it only affect the beats/lumberjack code.

Let me give you a bit of background:

The problem is in the way the lumberjack protocol works and how the clients are designed, if the server doesn't send an ack to the client, the client will think something went wrong and try to reconnect and send his packets again (He has a connection timeout).

 The server was stuck because the queue was blocked and the thread wasn't released. The client kept connecting to the server creating new threads and eventually made logstash OOM.

The current design of the queue doesn't have a concept of a timeout on push, this problem is mostly relevant to the TCP family of the inputs.

**Comment by guyboertje** [comment] 2015-11-19 15:32
Timeout on push can be done with two threads and a SizedQueue of 1. The caller starts a timeout thread and a worker thread both with access to the SizedQueueOfOne and then waits on the SizedQueueOfOne. The worker thread pushes the event (maybe waits for access) and when done puts something in the SizedQueueOfOne. The timeout thread sleeps for Timeout and then puts something in the SizedQueueOfOne. Whichever thread completes first frees the calling thread - bingo, exception free timeouts.  If the worker thread dies the timeout thread will still free the calling thread.

**Comment by ph** [comment] 2015-11-19 15:38
@guyboertje I would like to sync on that, not sure I understand all your description.

**Comment by guyboertje** [comment] 2015-11-19 17:31
@ppf2 - What do you consider a 'real-time' minimum setting to be?

**Comment by ppf2** [comment] 2015-11-20 06:23
@guyboertje I guess it depends on the performance implications of the flush :)  If its pretty lightweight, we can probably set the limit to something that is no more frequent than 1s or 5s, etc..

**Comment by guyboertje** [comment] 2015-12-21 17:51
Fixed in #18

**Closed as completed by guyboertje** 2015-12-21 17:51 UTC
Labels: enhancement
